x-env: &env
  SERVICE_ADDRESS: 0.0.0.0
  SERVICE_PORT: "8083"
  SERVICE_DIST: /dist
  SERVICE_DATA: /data
  SERVICE_OIDC_DISCOVERY_URL: ""
  SERVICE_OIDC_CLIENT_ID: ""
  INFINITY_PORT: "8002"
  SERVICE_INFINITY_ADDRESS: http://infinity:${INFINITY_PORT}
  SERVICE_INFINITY_IMAGE_MODEL: wkcn/TinyCLIP-ViT-8M-16-Text-3M-YFCC15M
  SERVICE_INFINITY_TEXT_MODEL: wkcn/TinyCLIP-ViT-8M-16-Text-3M-YFCC15M

services:
  corrugation:
    image: ghcr.io/w-floyd/corrugation:latest
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    restart: unless-stopped
    environment:
      <<: *env
      SERVICE_OIDC_INSECURE_SKIP_VERIFY: "false"
    volumes:
      - ./data/corrugation:/data
    depends_on:
      - infinity
  infinity:
    image: michaelf34/infinity:latest
    ports:
      - ${INFINITY_PORT}:${INFINITY_PORT}
    environment:
      <<: *env
    command: v2 --engine torch --device cpu --model-id ${SERVICE_INFINITY_IMAGE_MODEL} --model-id ${SERVICE_INFINITY_TEXT_MODEL} --port ${INFINITY_PORT} --log-level warning
    restart: unless-stopped
    volumes:
      - ./data/infinity/:/app/.cache
